noodle:
  property: Noodle Profile Dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/noodleDB
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true